#!/bin/bash
TICKET='5837'
BNAME='test001'
UMV='vn11.0'
USER='danielellis'
# user is the long fullname
LOC='~/dev/'


fcm branch-create -k $TICKET $BNAME fcm:um.x_tr@$UMV;

cd $LOC && fcm checkout fcm:um.x_br/dev/$USER/${UMV}_$BNAME;
